name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - 
      name: Checkout source
      uses: actions/checkout@v2
       
    - 
      name: Build with Maven
      run: mvn -B package --file pom.xml        

    -
      name: Build Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/kausri/image-repo/calc:latest --build-arg JAR_FILE=/target/Java-GitActions-0.0.1-SNAPSHOT-sources.jar     
    -
      name: Upload/ archive docker image 
      uses: ishworkh/docker-image-artifact-upload@v1
      with:
        image: ghcr.io/kausri/image-repo/calc:latest

#       uses: actions/upload-artifact@v2
#       with:
#           name: 'My Docker Image'
#           path: ./
#     - uses: actions/upload-artifact@master
#       with:
#         name: 'image'
#         path: public
         
           
#     - 
#       name: Login to github docker registry
#       uses: docker/login-action@v1
#       with:
# #         username: ${{github.actor}}
# #         password: ${{secrets.GITHUB_TOKEN}}
# #         registry: docker.pkg.github.com        
# #         tag_with_sha: true  
#         username: ${{github.actor}}
#         password: ${{secrets.GITHUB_TOKEN}}}
#         registry: docker.pkg.github.com
#         repository: kausri/github-actions-for-packages/calc
#         tag_with_ref: true    

    - 
      name: Download built artifact
      uses: ishworkh/docker-image-artifact-download@v1
      with:
        image: ghcr.io/kausri/image-repo/calc:latest
    -
      name: Build and push      
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: ghcr.io/kausri/image-repo/calc:latest
        registry: ghcr.io
        username: ${{ secrets.github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}         
        dockerfile: ./Dockerfile 
        tag: latest
        buildArgs: JAR_FILE=/target/Java-GitActions-0.0.1-SNAPSHOT-sources.jar
        

# 'image', 'tags', 'registry', 'dockerfile', 'directory', 'buildArgs', 'username', 'password', 'gitHubOrg'
      
#     -
#       name: publish docker image
#       run: docker push docker.pkg.github.com/kausri/kausri/github-actions-for-packages/calc:latest


