name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - 
        name: checkout 
        uses: actions/checkout@v2
        
      - 
        name: Build with Maven
        run: mvn -B package --file pom.xml        

      - 
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ github.token }}
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
          
          
      - 
        name: Build and tag Docker image
        run: docker build . --file Dockerfile --tag docker.pkg.github.com/kausri/image-repo/calc:1.0 --build-arg JAR_FILE=/target/Java-GitActions-0.0.1-SNAPSHOT-sources.jar
        
      - 
        name: Push docker image
        run: docker push docker.pkg.github.com/kausri/image-repo/calc:latest
