name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - 
      name: Checkout source
      uses: actions/checkout@v2
       
    - 
      name: Build with Maven
      run: mvn -B package --file pom.xml        

    -
      name: Build Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/kausri/image-repo/calc:latest --build-arg JAR_FILE=/target/Java-GitActions-0.0.1-SNAPSHOT-sources.jar     
            
    - 
      name: Login to github docker registry
      uses: docker/login-action@v1
      with:
        name: kausri/image-repo/calc
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ github.token }}
        
    -
      name: publish docker image
      run: docker push docker.pkg.github.com/kausri/image-repo/calc:latest
