# Test
name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - 
      name: Checkout source
      uses: actions/checkout@v2
       
    - 
      name: Build with Maven
      run: mvn -B package --file pom.xml        

    -
      name: Build Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/kausri/image-repo/calc:latest --build-arg JAR_FILE=/target/Java-GitActions-0.0.1-SNAPSHOT-sources.jar     
    

    - name: Push image
      run: |
        docker login ghcr.io -u ${{github.actor}} --password ${{secrets.GITHUB_TOKEN}}
        docker push ghcr.io/kausri/image-repo/calc:latest














#     - name: Log into registry
#       uses: docker/login-action@v1         
#       with: 
#         username: ${{github.actor}}
#         password: ${{secrets.GITHUB_TOKEN}}

#     -
#       name: Upload/ archive docker image 
#       uses: ishworkh/docker-image-artifact-upload@v1
#       with:
#         image: ghcr.io/kausri/image-repo/calc:latest

#     - 
#       name: Download built artifact
#       uses: ishworkh/docker-image-artifact-download@v1
#       with:
#         image: ghcr.io/kausri/image-repo/calc:latest
#     -
#       name: Build and push      
#       uses: mr-smithers-excellent/docker-build-push@v5
#       with:
#         image: ghcr.io/kausri/image-repo/calc
#         registry: ghcr.io
#         username: ${{ secrets.GHCR_USERNAME }}
#         password: ${{ secrets.GHCR_TOKEN }}         
#         dockerfile: ./Dockerfile 
#         buildArgs: JAR_FILE=/target/Java-GitActions-0.0.1-SNAPSHOT-sources.jar
        

#     - name: Build container image
#       uses: docker/build-push-action@v2
#       with:
#         context: ./
#         username: ${{github.actor}}
#         password: ${{secrets.GITHUB_TOKEN}}
#         registry: ghcr.io
# #         repository: kausri/image-repo/calc
#         repository: kausri/github-actions-for-packages/calc
# #         image: ghcr.io/kausri/image-repo/calc
# #         username: ${{ secrets.GHCR_USERNAME }}
# #         password: ${{ secrets.GHCR_TOKEN }}         
#         file: Dockerfile 
#         buildArgs: JAR_FILE=/target/Java-GitActions-0.0.1-SNAPSHOT-sources.jar
#         tags: latest
#         tag_with_sha: true

  
#     -   
#       name: Checkout
#       uses: actions/checkout@v1
#     - 
#       name: Download built artifact
#       uses: ishworkh/docker-image-artifact-download@v1
#       with:
#         image: ghcr.io/kausri/image-repo/calc:latest

#     - name: Push downloaded docker image
#       with:
#         username: ${{github.actor}}
#         password: ${{secrets.GITHUB_TOKEN}}
#   #         registry: docker.pkg.github.com
#         registry: ghcr.io
#         repository: kausri/image-repo/calc
#         tag_with_sha: true
#         docker push ghcr.io/kausri/image-repo/calc:latest
