name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - 
      name: Checkout source
      uses: actions/checkout@v2
       
    - 
      name: Build with Maven
      run: mvn -B package --file pom.xml        

    -
      name: Build Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/kausri/image-repo/calc:latest --build-arg JAR_FILE=/target/Java-GitActions-0.0.1-SNAPSHOT-sources.jar     
    -
      name: Archive docker image 
      uses: actions/upload-artifact@v2
      with:
          name: 'My Docker Image'
          path: ./
#     - uses: actions/upload-artifact@master
#       with:
#         name: 'image'
#         path: public
         
           
#     - 
#       name: Login to github docker registry
#       uses: docker/login-action@v1
#       with:
# #         username: ${{github.actor}}
# #         password: ${{secrets.GITHUB_TOKEN}}
# #         registry: docker.pkg.github.com        
# #         tag_with_sha: true  
#         username: ${{github.actor}}
#         password: ${{secrets.GITHUB_TOKEN}}}
#         registry: docker.pkg.github.com
#         repository: kausri/github-actions-for-packages/calc
#         tag_with_ref: true    

    - 
      name: Download built artifact
      uses: actions/download-artifact@v1
      with:
        name: 'My Docker Image'
        path: ./
    -
      name: Build and push      
      id: docker_build
      uses: docker/build-push-action@v1
      with:
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
#         registry: docker.pkg.github.com
        registry: ghcr.io
        repository: kausri/image-repo/calc
#         context: ./
#         file: ./Dockerfile 
#         build-args: JAR_FILE=/target/Java-GitActions-0.0.1-SNAPSHOT-sources.jar
        tag_with_sha: true
#         tags: ghcr.io/kausri/image-repo/calc:latest
#         tags: ghcr.io/kausri/image-repo/calc:latest

      
#     -
#       name: publish docker image
#       run: docker push docker.pkg.github.com/kausri/kausri/github-actions-for-packages/calc:latest


